import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import sys, os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "modules"))

DB_PATH = os.path.join(os.path.dirname(__file__), "data", "growthens.db")
if not os.path.exists(DB_PATH):
    os.makedirs(os.path.join(os.path.dirname(__file__), "data"), exist_ok=True)
    from data_generator import generate_all
    generate_all()

from crm_retention import (load_rfm_data, get_segment_summary,
                            train_churn_model, simulate_campaign_roi,
                            get_market_breakdown)
from ab_testing   import (load_experiment_data, run_ztest, explain,
                          sample_size_per_group)
from pricing_opt  import (load_data, get_revenue_summary,
                           get_base_values, optimize_discount,
                           explain_discount, format_eur_change,
                           get_channel_roi, format_roi,
                           ELASTICITY_NOTE, PRICE_TEST_NOTE)

# ── Page config ──────────────────────────────────────────────────
st.set_page_config(
    page_title = "GrowthLens",
    page_icon  = "🔭",
    layout     = "wide",
)

# ── Colour palette ───────────────────────────────────────────────
GREEN  = "#1D9E75"
PURPLE = "#7F77DD"
AMBER  = "#EF9F27"
RED    = "#E05C5C"
BLUE   = "#378ADD"
SEG_COLOURS = {
    "VIP"             : BLUE,
    "Loyal"           : GREEN,
    "Needs Attention" : AMBER,
    "Lost"            : RED,
    "At Risk"         : "#E07A5F",
    "Recent one-time buyer" : PURPLE,
    "Never booked"    : "#9AA0A6",
}

# ── Cache heavy computations ─────────────────────────────────────
@st.cache_data
def load_all():
    rfm              = load_rfm_data()
    segment_summary  = get_segment_summary(rfm)
    rfm_scored, churn_metrics, importance, churn_holdout = train_churn_model(rfm)
    exp_raw          = load_experiment_data()
    bookings, mkt    = load_data()
    by_market, by_cat= get_revenue_summary(bookings)
    ch_roi           = get_channel_roi(mkt)
    ab_results       = [run_ztest(exp_raw, e)
                        for e in exp_raw['experiment'].unique()]
    return (rfm_scored, segment_summary, churn_metrics, importance, churn_holdout,
            exp_raw, ab_results,
            bookings, by_market, by_cat,
            ch_roi)

# ── Sidebar navigation ───────────────────────────────────────────
st.sidebar.image("https://img.icons8.com/fluency/96/telescope.png", width=64)
st.sidebar.title("GrowthLens")
st.sidebar.caption("Growth Analytics Platform")
st.sidebar.divider()

page = st.sidebar.radio(
    "Navigate",
    ["Executive Summary", "CRM & Retention",
     "A/B Testing", "Pricing & Revenue"],
    label_visibility="collapsed",
)

st.sidebar.divider()
st.sidebar.caption("Built with Python · SQL · Streamlit")
st.sidebar.caption("Yigit Uysaloglu · 2025–2026")

# ── Load data ────────────────────────────────────────────────────
with st.spinner("Loading GrowthLens data..."):
    (rfm, seg_summary, churn_metrics, importance, churn_holdout,
     exp_raw, ab_results,
     bookings, by_market, by_cat,
     ch_roi) = load_all()


# ════════════════════════════════════════════════════════════════
# PAGE 1 — EXECUTIVE SUMMARY
# ════════════════════════════════════════════════════════════════
if page == "Executive Summary":
    st.title("🔭 GrowthLens — Executive Summary")
    st.caption("Travel marketplace growth analytics · 50,000 customers · 24 months")
    st.caption("Synthetic data generated by modules/data_generator.py")
    st.divider()

    # ── Top KPI row ──────────────────────────────────────────────
    total_customers = len(rfm)
    total_revenue   = rfm['total_spend_eur'].sum()
    vip_count       = len(rfm[rfm['rfm_segment'] == 'VIP'])
    at_risk_rev     = rfm[rfm['rfm_segment'].isin(
                          ['At Risk','Needs Attention'])]['total_spend_eur'].sum()

    k1, k2, k3, k4 = st.columns(4)
    k1.metric("Total Customers",   f"{total_customers:,}")
    k2.metric("Total Revenue",     f"€{total_revenue:,.0f}")
    k3.metric("VIP Customers",     f"{vip_count:,}",
              f"{vip_count/total_customers*100:.1f}% of base")
    k4.metric("At-Risk Revenue",   f"€{at_risk_rev:,.0f}",
              "needs retention action", delta_color="inverse")

    st.divider()
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Customer segments")
        seg_plot = seg_summary.copy()
        fig = px.bar(
            seg_plot, x="rfm_segment", y="customer_count",
            color="rfm_segment",
            color_discrete_map=SEG_COLOURS,
            text="customer_count",
            labels={"rfm_segment":"Segment","customer_count":"Customers"},
        )
        fig.update_traces(texttemplate='%{text:,}', textposition='outside')
        fig.update_layout(showlegend=False, height=340,
                          plot_bgcolor='rgba(0,0,0,0)',
                          paper_bgcolor='rgba(0,0,0,0)')
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        st.subheader("Revenue by segment")
        fig2 = px.pie(
            seg_summary[seg_summary['total_revenue'] > 0],
            values="total_revenue", names="rfm_segment",
            color="rfm_segment", color_discrete_map=SEG_COLOURS,
            hole=0.45,
        )
        fig2.update_layout(height=340,
                           paper_bgcolor='rgba(0,0,0,0)')
        st.plotly_chart(fig2, use_container_width=True)

    # ── Revenue by market ─────────────────────────────────────────
    st.subheader("Revenue by market")
    fig3 = px.bar(
        by_market, x="market", y="total_revenue",
        color="total_revenue", color_continuous_scale="Teal",
        text="total_revenue",
        labels={"market":"Market","total_revenue":"Revenue (€)"},
    )
    fig3.update_traces(
        texttemplate='€%{text:,.0f}', textposition='outside'
    )
    fig3.update_layout(
        showlegend=False, height=320,
        coloraxis_showscale=False,
        plot_bgcolor='rgba(0,0,0,0)',
        paper_bgcolor='rgba(0,0,0,0)',
    )
    st.plotly_chart(fig3, use_container_width=True)


# ════════════════════════════════════════════════════════════════
# PAGE 2 — CRM & RETENTION
# ════════════════════════════════════════════════════════════════
elif page == "CRM & Retention":
    st.title("👥 CRM & Retention")
    st.caption("RFM segmentation · Churn prediction · Campaign simulator")
    st.divider()

    tab1, tab2, tab3 = st.tabs(
        ["Segment Explorer", "Churn Model", "Campaign Simulator"]
    )

    # ── Tab 1: Segment Explorer ───────────────────────────────────
    with tab1:
        col1, col2 = st.columns([1, 2])
        with col1:
            selected_seg = st.selectbox(
                "Select segment", rfm['rfm_segment'].unique()
            )
            seg_data = rfm[rfm['rfm_segment'] == selected_seg]
            st.metric("Customers",    f"{len(seg_data):,}")
            st.metric("Avg spend",    f"€{seg_data['total_spend_eur'].mean():,.0f}")
            st.metric("Avg bookings", f"{seg_data['total_bookings'].mean():.1f}")
            st.metric("Avg recency",  f"{seg_data['recency_days'].mean():.0f} days")

        with col2:
            st.subheader("RFM score distribution")
            fig = px.histogram(
                seg_data, x="rfm_score", nbins=10,
                color_discrete_sequence=[SEG_COLOURS.get(selected_seg, GREEN)],
                labels={"rfm_score": "RFM Score"},
            )
            fig.update_layout(height=300,
                              plot_bgcolor='rgba(0,0,0,0)',
                              paper_bgcolor='rgba(0,0,0,0)')
            st.plotly_chart(fig, use_container_width=True)

        st.subheader("Segment comparison")
        fig2 = px.scatter(
            rfm.sample(min(3000, len(rfm))),
            x="recency_days", y="total_spend_eur",
            color="rfm_segment", size="total_bookings",
            color_discrete_map=SEG_COLOURS,
            opacity=0.6,
            labels={"recency_days":"Days since last booking",
                    "total_spend_eur":"Total spend (€)",
                    "rfm_segment":"Segment"},
        )
        fig2.update_layout(height=380,
                           plot_bgcolor='rgba(0,0,0,0)',
                           paper_bgcolor='rgba(0,0,0,0)')
        st.plotly_chart(fig2, use_container_width=True)

    # ── Tab 2: Churn Model ────────────────────────────────────────
    with tab2:
        col1, col2 = st.columns(2)
        with col1:
            st.caption(
                f"Trained on bookings before {churn_metrics['cutoff']}; churn = no booking "
                f"in the next {churn_metrics['horizon_days']} days. Scores below use the "
                f"full history up to 2024-12-31."
            )
            m1, m2, m3 = st.columns(3)
            m1.metric("Model AUC", f"{churn_metrics['model_auc']:.3f}",
                      "1.0 = perfect · 0.5 = random", delta_color="off")
            m2.metric("Baseline AUC", f"{churn_metrics['baseline_auc']:.3f}",
                      "recency only", delta_color="off")
            m3.metric("Churners in top 10%",
                      f"{churn_metrics['model_top10_hits']:,} / {churn_metrics['top10_size']:,}",
                      f"baseline {churn_metrics['baseline_top10_hits']:,} · "
                      f"random ≈ {churn_metrics['random_top10_hits']:.0f}",
                      delta_color="off")
            st.subheader("Feature importance")
            fig = px.bar(
                importance, x="importance", y="feature",
                orientation='h',
                color="importance",
                color_continuous_scale="Teal",
                labels={"importance":"Importance","feature":"Feature"},
            )
            fig.update_layout(
                height=340, showlegend=False,
                coloraxis_showscale=False,
                plot_bgcolor='rgba(0,0,0,0)',
                paper_bgcolor='rgba(0,0,0,0)',
                yaxis={'categoryorder':'total ascending'},
            )
            st.plotly_chart(fig, use_container_width=True)

        with col2:
            st.subheader("Churn probability distribution")
            fig2 = px.histogram(
                rfm[rfm['churn_probability'] > 0],
                x="churn_probability", nbins=40,
                color_discrete_sequence=[PURPLE],
                labels={"churn_probability":"Churn probability"},
            )
            fig2.update_layout(height=380,
                               plot_bgcolor='rgba(0,0,0,0)',
                               paper_bgcolor='rgba(0,0,0,0)')
            st.plotly_chart(fig2, use_container_width=True)

        st.subheader("Highest churn risk customers")
        top_churn = (rfm.sort_values('churn_probability', ascending=False)
                     [['customer_id','market','rfm_segment',
                        'total_bookings','total_spend_eur','churn_probability']]
                     .head(10))
        st.dataframe(top_churn, use_container_width=True, hide_index=True)

    # ── Tab 3: Campaign Simulator ─────────────────────────────────
    with tab3:
        st.subheader("Win-back campaign simulator")
        st.caption("Targets opted-in customers with the highest churn score. "
                   "Only re-bookings caused by the campaign are counted.")

        target_pct = st.slider("Target top % of opted-in customers by churn score",
                               5, 100, 20) / 100

        st.markdown("**Assumptions** — not measured in the data, set them yourself")
        a1, a2, a3, a4 = st.columns(4)
        uplift     = a1.slider("Assumption: campaign uplift (pp)", 0.0, 10.0, 2.0,
                               step=0.5,
                               help="Extra share of targeted customers who re-book "
                                    "because of the email") / 100
        margin     = a2.slider("Assumption: profit margin %", 5, 60, 20) / 100
        cost_email = a3.slider("Assumption: cost per email (€)",
                               0.01, 0.50, 0.05, step=0.01)
        discount   = a4.slider("Assumption: discount per booking %", 0, 30, 0,
                               help="Given to every targeted customer who books, "
                                    "including those who would have booked anyway") / 100

        roi = simulate_campaign_roi(rfm, churn_holdout, target_pct, uplift,
                                    margin, cost_email, discount)

        st.caption(
            f"From the data: {roi['n_eligible']:,} opted-in customers have a churn score · "
            f"avg booking value of targeted customers €{roi['avg_booking_value']:,.2f} · "
            f"{roi['baseline_rate']*100:.1f}% of similar customers re-booked within "
            f"{churn_metrics['horizon_days']} days with no campaign"
        )

        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Targeted",          f"{roi['n_targeted']:,}")
        m2.metric("Would book anyway", f"{roi['would_book_anyway']:,.0f}",
                  "not credited to campaign", delta_color="off")
        m3.metric("Extra re-bookings", f"{roi['extra_rebookings']:,.0f}")
        def eur(x):
            # Sign before the currency symbol so losses read as -€1,234.
            return f"-€{abs(x):,.0f}" if x < 0 else f"€{x:,.0f}"

        m4.metric("Extra profit",      eur(roi['extra_profit']),
                  f"revenue €{roi['extra_revenue']:,.0f}", delta_color="off")

        m5, m6, m7, m8 = st.columns(4)
        m5.metric("Email cost",        f"€{roi['email_cost']:,.0f}")
        m6.metric("Discounts to 'would book anyway'",
                  f"€{roi['anyway_discount_cost']:,.0f}")
        m7.metric("Net profit",        eur(roi['net_profit']))
        roi_text = "n/a" if pd.isna(roi['roi_pct']) else f"{roi['roi_pct']:.0f}%"
        m8.metric("ROI on profit",     roi_text)

        breakdown = pd.DataFrame({
            "Group": ["Targeted", "Would book anyway", "Extra from campaign"],
            "Customers": [roi['n_targeted'], roi['would_book_anyway'],
                          roi['extra_rebookings']],
        })
        fig = px.bar(breakdown, x="Customers", y="Group", orientation='h',
                     color="Group",
                     color_discrete_sequence=[BLUE, AMBER, GREEN])
        fig.update_layout(height=260, showlegend=False,
                          yaxis={'categoryorder': 'array',
                                 'categoryarray': breakdown["Group"][::-1].tolist()},
                          plot_bgcolor='rgba(0,0,0,0)',
                          paper_bgcolor='rgba(0,0,0,0)')
        st.plotly_chart(fig, use_container_width=True)

        st.info("Uplift here is an assumption. The real effect must be measured with "
                "a holdout group: an A/B test where a random part of the target list "
                "gets no email, and the difference in re-booking between the two "
                "groups is the uplift.")


# ════════════════════════════════════════════════════════════════
# PAGE 3 — A/B TESTING
# ════════════════════════════════════════════════════════════════
elif page == "A/B Testing":
    st.title("🧪 A/B Testing")
    st.caption("Statistical significance · Z-test · CPA analysis")
    st.divider()

    for r in ab_results:
        sig_colour = GREEN if r['is_significant'] else RED
        sig_label  = "✓ Significant" if r['is_significant'] else "✗ Not significant"

        with st.expander(
            f"**{r['experiment'].replace('_',' ').title()}** — "
            f"Lift: {r['lift_pct']:+.1f}% — {sig_label}",
            expanded=True,
        ):
            col1, col2, col3, col4 = st.columns(4)
            col1.metric("Z-score",    f"{r['z_score']}",
                        "threshold ±1.96")
            col2.metric("P-value",    f"{r['p_value']}",
                        "threshold 0.05")
            col3.metric("Lift",       f"{r['lift_pct']:+.1f}%",
                        f"95% CI {r['lift_low_pct']:+.1f}% to {r['lift_high_pct']:+.1f}%",
                        delta_color="off")
            col4.metric("Significant",sig_label)

            col5, col6, col7, col8 = st.columns(4)
            col5.metric("Difference", f"{r['diff_pp']:+.2f} pp",
                        f"95% CI {r['diff_low_pp']:+.2f} to {r['diff_high_pp']:+.2f} pp",
                        delta_color="off")
            col6.metric("Sample ratio",
                        "OK" if r['srm_ok'] else "MISMATCH",
                        f"{r['control_share']*100:.1f}% control · p = {r['srm_p_value']:.2f}",
                        delta_color="off")
            if 'power_at_true_effect' in r:
                col7.metric("Power (planted effect)",
                            f"{r['power_at_true_effect']*100:.0f}%",
                            f"{r['n_control']:,} / {r['n_test']:,} users", delta_color="off")
                col8.metric("Needed for 80% power", f"{r['n_needed_80']:,} / group",
                            f"90%: {r['n_needed_90']:,} / group", delta_color="off")

            if 'true_lift_pct' in r:
                truth_text = (
                    f"**Planted truth (synthetic data):** {r['true_rate_control_pct']:.1f}% → "
                    f"{r['true_rate_test_pct']:.1f}% ({r['true_lift_pct']:+.1f}%). "
                    f"Measured {r['lift_pct']:+.1f}%; the 95% CI "
                    f"{'contains' if r['ci_contains_truth'] else 'does not contain'} the truth."
                )
                if r['missed_real_effect']:
                    st.error(truth_text + " **This test missed a real effect because it "
                             "was underpowered.**")
                else:
                    st.success(truth_text + " The verdict matches the truth.")

            c1, c2 = st.columns(2)
            with c1:
                # Conversion rate comparison
                comp = pd.DataFrame({
                    "Variant":         ["Control","Test"],
                    "Conversion rate": [r['rate_control_pct'],
                                        r['rate_test_pct']],
                    "CPA (€)":         [r['cpa_control'],
                                        r['cpa_test']],
                })
                fig = px.bar(
                    comp, x="Variant", y="Conversion rate",
                    color="Variant",
                    color_discrete_sequence=[BLUE, GREEN],
                    text="Conversion rate",
                    title="Conversion rate (%)",
                )
                fig.update_traces(
                    texttemplate='%{text:.3f}%', textposition='outside'
                )
                fig.update_layout(
                    showlegend=False, height=300,
                    plot_bgcolor='rgba(0,0,0,0)',
                    paper_bgcolor='rgba(0,0,0,0)',
                )
                st.plotly_chart(fig, use_container_width=True)

            with c2:
                fig2 = px.bar(
                    comp, x="Variant", y="CPA (€)",
                    color="Variant",
                    color_discrete_sequence=[BLUE, AMBER],
                    text="CPA (€)",
                    title="Cost per acquisition (€)",
                )
                fig2.update_traces(
                    texttemplate='€%{text:.2f}', textposition='outside'
                )
                fig2.update_layout(
                    showlegend=False, height=300,
                    plot_bgcolor='rgba(0,0,0,0)',
                    paper_bgcolor='rgba(0,0,0,0)',
                )
                st.plotly_chart(fig2, use_container_width=True)

            st.info(f"**Verdict:** {r['verdict']}")
            st.success(f"**Recommendation:** {r['recommendation']}")
            st.markdown("**In plain words**\n" + "\n".join(f"- {l}" for l in explain(r)))

    st.divider()
    st.subheader("Sample size calculator")
    st.caption("How many users each group needs before the test starts. "
               "Two-sided test at a 5% significance level.")
    s1, s2, s3 = st.columns(3)
    base_rate = s1.number_input("Baseline conversion rate (%)", 0.1, 90.0, 2.0,
                                step=0.1) / 100
    mde       = s2.number_input("Minimum detectable effect (relative lift %)",
                                1.0, 200.0, 20.0, step=1.0) / 100
    power     = s3.radio("Power", ["80%", "90%"], horizontal=True)
    target_rate = base_rate * (1 + mde)
    if target_rate >= 1:
        st.warning("Baseline × (1 + effect) must stay below 100%.")
    else:
        n_needed = sample_size_per_group(base_rate, target_rate,
                                         0.80 if power == "80%" else 0.90)
        r1, r2 = st.columns(2)
        r1.metric("Users per group", f"{n_needed:,}")
        r2.metric("Users in total", f"{2 * n_needed:,}")
        st.caption(f"Detects {base_rate*100:.2f}% → {target_rate*100:.2f}% "
                   f"({target_rate*100 - base_rate*100:+.2f} pp) with {power} power.")


# ════════════════════════════════════════════════════════════════
# PAGE 4 — PRICING & REVENUE
# ════════════════════════════════════════════════════════════════
elif page == "Pricing & Revenue":
    st.title("💰 Pricing & Revenue")
    st.caption("Revenue breakdown · Discount scenarios (assumed elasticity) · Channel ROI")
    st.divider()

    tab1, tab2, tab3 = st.tabs(
        ["Revenue breakdown", "Discount optimizer", "Channel ROI"]
    )

    with tab1:
        col1, col2 = st.columns(2)
        with col1:
            st.subheader("Revenue by market")
            fig = px.bar(
                by_market, x="market", y="total_revenue",
                color="total_revenue",
                color_continuous_scale="Teal",
                text="total_revenue",
            )
            fig.update_traces(
                texttemplate='€%{text:,.0f}', textposition='outside'
            )
            fig.update_layout(
                height=360, showlegend=False,
                coloraxis_showscale=False,
                plot_bgcolor='rgba(0,0,0,0)',
                paper_bgcolor='rgba(0,0,0,0)',
            )
            st.plotly_chart(fig, use_container_width=True)

        with col2:
            st.subheader("Revenue by category")
            fig2 = px.pie(
                by_cat, values="total_revenue", names="category",
                hole=0.4,
                color_discrete_sequence=px.colors.qualitative.Set2,
            )
            fig2.update_layout(height=360,
                               paper_bgcolor='rgba(0,0,0,0)')
            st.plotly_chart(fig2, use_container_width=True)

    with tab2:
        st.subheader("Discount optimisation curve")
        st.info(ELASTICITY_NOTE)

        st.markdown("**Assumptions** — not measured in the data, set them yourself")
        a1, a2 = st.columns(2)
        elasticity = a1.slider("Assumption: price elasticity", 0.0, 5.0, 1.0, step=0.1,
                               help="% more bookings for every 1% price cut")
        margin     = a2.slider("Assumption: profit margin %", 5, 60, 20) / 100

        data_price, data_vol = get_base_values(bookings)
        b1, b2 = st.columns(2)
        base_price = b1.slider("Base price (€) — data average", 30, 250,
                               int(round(data_price)))
        base_vol   = b2.slider("Base monthly bookings — data average", 500, 10000,
                               int(round(data_vol)))

        curve, best_rev, best_profit = optimize_discount(
            base_price, base_vol, elasticity, margin
        )

        k1, k2, k3 = st.columns(3)
        k1.metric("Revenue-optimal discount", f"{best_rev['discount_pct']:.0f}%")
        k2.metric("Profit-optimal discount",  f"{best_profit['discount_pct']:.0f}%")
        k3.metric("Monthly profit change at that discount",
                  format_eur_change(best_profit["profit_change_eur"]))

        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=curve['discount_pct'], y=curve['revenue_change_eur'],
            mode='lines', name='Revenue change',
            line=dict(color=GREEN, width=2.5),
        ))
        fig.add_trace(go.Scatter(
            x=curve['discount_pct'], y=curve['profit_change_eur'],
            mode='lines', name='Profit change',
            line=dict(color=PURPLE, width=2.5),
        ))
        fig.add_hline(y=0, line_color=AMBER, line_dash='dash',
                      annotation_text="No discount")
        fig.update_layout(
            height=380,
            xaxis_title="Discount %",
            yaxis_title="Monthly change vs no discount (€)",
            plot_bgcolor='rgba(0,0,0,0)',
            paper_bgcolor='rgba(0,0,0,0)',
            legend=dict(orientation='h', y=1.1),
        )
        st.plotly_chart(fig, use_container_width=True)

        st.markdown("**Why this discount?**\n" + "\n".join(
            f"- {l}" for l in explain_discount(elasticity, margin, best_rev, best_profit)))
        st.warning(PRICE_TEST_NOTE)

    with tab3:
        st.subheader("Channel performance")
        fig = px.bar(
            ch_roi, x="channel", y="total_revenue",
            color="channel",
            color_discrete_sequence=[GREEN, PURPLE, AMBER],
            text="total_revenue",
            labels={"channel":"Channel","total_revenue":"Revenue (€)"},
        )
        fig.update_traces(
            texttemplate='€%{text:,.0f}', textposition='outside'
        )
        fig.update_layout(
            showlegend=False, height=340,
            plot_bgcolor='rgba(0,0,0,0)',
            paper_bgcolor='rgba(0,0,0,0)',
        )
        st.plotly_chart(fig, use_container_width=True)
        roi_table = ch_roi.assign(roi_pct=ch_roi['roi_pct'].map(format_roi))
        st.dataframe(roi_table, use_container_width=True, hide_index=True)